(ns euler.ex12
  {:author "KGZM"}
  (:require [euler.ex9 :refer [factor]]
            [clojure.test :refer :all]))

;; The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
;; 
;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;; 
;; Let us list the factors of the first seven triangle numbers:
;; 
;; 1: 1
;; 3: 1,3
;; 6: 1,2,3,6
;; 10: 1,2,5,10
;; 15: 1,3,5,15
;; 21: 1,3,7,21
;; 28: 1,2,4,7,14,28
;; We can see that 28 is the first triangle number to have over five divisors.
;; 
;; What is the value of the first triangle number to have over five hundred divisors?

(defn triangle-numbers []
  (for [n (drop 1 (range)) ] 
    (reduce + (range 1 (inc n)))))

(defn first-triangle-number-by-divisors [n]
  (first (filter (comp (partial <= n)
                       count
                       set
                       flatten
                       factor)
                 (triangle-numbers))))


(deftest given-solution
  (is (= 28 (first-triangle-number-by-divisors 5))))

(comment 
  (first-triangle-number-by-divisors 500);;=>  76576500
  )
