(ns euler.ex2
  (:require [clojure.test :refer :all]))

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn fibonacci []
 (let [generator  
       (fn generator [a b] 
         (cons a (lazy-seq (generator b (+ a b)))))]
   (generator 1 2)))

(defn solution []
  (->> (take-while (partial > 4000000) (fibonacci))
       (filter even?)
       (reduce +)))
(comment 
  (solution) ;4613732
  )
  
